name: DeepPurpose
channels:
  - rdkit
  - pytorch
  - rmg
  - conda-forge
  - defaults
dependencies:
  - attrs
  - backcall
  - blas
  - bleach
  - botorch
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - cycler
  - decorator
  - defusedxml
  - descriptastorus
  - entrypoints
  - fontconfig
  - freetype
  - gettext
  - gpytorch
  - icu
  - importlib-metadata
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - jedi
  - jinja2
  - joblib
  - jpeg
  - jsonschema
  - jupyter_client
  - jupyter_core
  - kiwisolver
  - libblas
  - libboost
  - libcblas
  - libffi
  - libiconv
  - liblapack
  - libpng
  - libsodium
  - libtiff
  - libxml2
  - llvm-openmp
  - lz4
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - nbconvert
  - nbformat
  - ninja
  - notebook
  - numpy
  - numpy-base
  - olefile
  - openssl
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pixman
  - prometheus_client
  - prompt-toolkit
  - ptyprocess
  - py-boost
  - pycparser
  - pygments
  - pyparsing
  - pyrsistent
  - python
  - python-dateutil
  - python_abi
  - pytorch
  - pytz
  - pyzmq
  - scikit-learn
  - scikit-plot
  - scipy
  - seaborn
  - send2trash
  - setuptools
  - six
  - sqlite
  - tensorboard
  - terminado
  - testpath
  - tk
  - torchvision
  - tornado
  - tqdm
  - traitlets
  - wcwidth
  - webencodings
  - wheel
  - xz
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
      - alabaster
      - autograd
      - autograd-gamma
      - ax-platform
      - babel
      - chardet
      - docutils
      - future
      - idna
      - imagesize
      - lifelines
      - packaging
      - prettytable
      - requests
      - snowballstemmer
      - subword-nmt
      - urllib3
      - wget